#!/bin/sh

# Автозапуск програм
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &
pgrep -x picom > /dev/null || picom &

# Налаштування моніторів
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10

# Конфігурація вікон
bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Кольори
bspc config normal_border_color  "#444444"
bspc config active_border_color  "#9fbc00"
bspc config focused_border_color "#ff6600"
bspc config presel_feedback_color "#5e81ac"

# Правила для програм
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/Pictures/wallpaper.jpg
~/.config/polybar/launch.sh